# Generated by Django 4.2.8 on 2024-01-07 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudproj', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookModel',
            new_name='Book',
        ),
    ]
